export const mentorsData = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dXNlciUyMHByb2ZpbGV8ZW58MHx8MHx8&w=1000&q=80",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=800",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/7275385/pexels-photo-7275385.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/6962024/pexels-photo-6962024.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/6626882/pexels-photo-6626882.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/7148620/pexels-photo-7148620.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6831602/pexels-photo-6831602.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/6475046/pexels-photo-6475046.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/6195663/pexels-photo-6195663.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/6195663/pexels-photo-6195663.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 11,
    img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=800",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/6475046/pexels-photo-6475046.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 13,
    img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dXNlciUyMHByb2ZpbGV8ZW58MHx8MHx8&w=1000&q=80",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 14,
    img: "https://images.pexels.com/photos/6962024/pexels-photo-6962024.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 15,
    img: "https://images.pexels.com/photos/7275385/pexels-photo-7275385.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
  {
    id: 16,
    img: "https://images.pexels.com/photos/6195663/pexels-photo-6195663.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "Christian Solorzano",
    abreviation: "SE",
    work: "Cambio Group",
    role: "Sr. Experience Designer",
    interest: "Job search, Career advice, Leader...",
  },
];
